# -*- coding: utf-8 -*-
"""Cópia de Heve - IA - Exercício - 08 - Rede Neural Artificial - Python - SkLearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3-CidTI37V-Fh6W0YjWs1Hypqv4Xj_W

# Treinamento

### Carregando Arquivo de Treinamento (.csv)
"""

import pandas as pd
# Carregando dados do arquivo CSv
url = 'https://raw.githubusercontent.com/heveeedesouza/-classificador-Neural-Perceptron-para-a-doenca-de-Diabetes/main/dados_diabetes_treinamento.csv'
base_Treinamento = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

"""### Pré-processamento de Dados"""

import numpy as np

base_Treinamento = np.loadtxt('https://raw.githubusercontent.com/heveeedesouza/-classificador-Neural-Perceptron-para-a-doenca-de-Diabetes/main/dados_diabetes_treinamento.csv',delimiter=";",skiprows=1)

# Todas as colunas menos a última (Outcome)
atributos_norm = base_Treinamento[:, :8]

print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

# Última coluna (1 e 0)
diagnostico_norm = base_Treinamento[:, 8]

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
print(diagnostico_norm)

"""### Treinamento do Neurônio Perceptron"""

from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

"""### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples
"""

Luiz = np.array([[2, 130, 70, 28, 100, 31.0, 0.45, 35]])
print("Luiz:", modelo.predict(Luiz))

Laura = np.array([[0, 95, 60, 20, 80, 22.5, 0.20, 25]])
print("Laura:", modelo.predict(Laura))

"""### Predição a partir de base de dados (.csv)"""

import pandas as pd
# Carregando dados do arquivo CSV
url = "https://raw.githubusercontent.com/heveeedesouza/-classificador-Neural-Perceptron-para-a-doenca-de-Diabetes/main/dados_diabetes_teste.csv"


base_Testes = pd.read_csv(url,sep=';', encoding = 'latin1').values

#n usar a notação cientifica
np.set_printoptions(suppress=True)

print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 1:9])

"""### Pré-processamento de Dados"""

import numpy as np

atributos_norm = base_Testes[:, 0:8]

print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
#n usar a notação cientifica
np.set_printoptions(suppress=True)
print(atributos_norm)

"""### Predição da Base"""

base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

"""### Retorno aos valores Categóricos"""

import numpy as np


predicao = modelo.predict(atributos_norm)
predicao = predicao.reshape(-1, 1)

# concatena
atributos_cat = np.column_stack((atributos_norm, predicao))

print("--------------------------------")
print("Atributos de entrada + Predição")
print("--------------------------------")
#n usar a notação cientifica
np.set_printoptions(suppress=True)
print(atributos_cat)
